# Generated by Django 5.2.14 on 2026-06-06 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "interest_level",
                    models.CharField(
                        choices=[
                            ("hot", "Hot - Highly Interested"),
                            ("warm", "Warm - Somewhat Interested"),
                            ("cold", "Cold - Not Interested"),
                            ("followup", "Follow Up Required"),
                        ],
                        default="cold",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_date", models.DateField(auto_now_add=True)),
                ("call_time", models.TimeField(auto_now_add=True)),
                (
                    "call_duration",
                    models.DurationField(help_text="Duration in HH:MM:SS format"),
                ),
                (
                    "call_outcome",
                    models.CharField(
                        choices=[
                            ("connected", "Connected - Spoke to Client"),
                            ("no_answer", "No Answer"),
                            ("busy", "Busy"),
                            ("callback", "Requested Callback"),
                            ("wrong_number", "Wrong Number"),
                            ("not_interested", "Not Interested"),
                        ],
                        default="connected",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "called_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
