# Generated by Django 4.2.7 on 2026-06-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="interest_level",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("planning", "Planning Soon"),
                    ("followup", "Need to Follow Up"),
                    ("not_interested", "Not Interested"),
                ],
                default="followup",
                max_length=15,
            ),
        ),
    ]
